repos:
-   repo: local
    hooks:
    -   id: cppcheck
        name: cppcheck
        entry: cppcheck --error-exitcode=1 --enable=warning,style --std=c11 --suppress=missingIncludeSystem --inline-suppr -I 03_FreeRTOS/App/Inc
        language: system
        types: [c]
    -   id: lizard
        name: lizard
        entry: lizard -l 15 -C 10
        language: python
        additional_dependencies: [lizard]
        types: [c]