name: Test and Deploy Docs

on:
  push:
    branches: [ main ]  # Or 'master' depending on your default branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  quality-gate-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Ruby (for Jekyll)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install Lint/Metrics Tools
        run: |
          sudo apt-get install -y cppcheck
          pip install lizard

      - name: Run Quality Gate
        # If either of these fail, the deployment stops here
        run: |
          # 1. Define the base path to avoid typos
            BASE_PATH="03_FreeRTOS/App"

          # 2. Check if the directory exists before running tools
          if [ -d "$BASE_PATH" ]; then
            echo "üöÄ Running Cppcheck on $BASE_PATH..."

          # We add --suppress=unusedFunction to handle the FreeRTOS hooks
            cppcheck --enable=warning,style --error-exitcode=1 \
            --std=c11 \
            --inline-suppr \
            --suppress=missingIncludeSystem \
            --suppress=missingInclude \
            --suppress=unusedFunction \
            -I $BASE_PATH/Inc \
            $BASE_PATH/

          echo "üìà Running Lizard..."
            lizard -w -l 15 -C 10 $BASE_PATH/
          else
            echo "‚ö†Ô∏è Directory $BASE_PATH not found! Skipping checks."
            exit 1 # Fail the build if the folder is missing
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build Jekyll Site
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      needs: quality-gate-and-build
      steps:
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4